name: CI

on:
  repository_dispatch:
    types: trigger-ci
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  ci-workflow:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: Simple-Calculator-master
      continue-on-error: true
    - run: npm test 
      working-directory: Simple-Calculator-master
      continue-on-error: true
    - name: Notify Webhook
      if: ${{ github.event.client_payload && github.event.client_payload.post_url != '' }}
      run: |
        curl -X POST ${{ github.event.client_payload.post_url }} \
        -H "Content-Type: application/json" \
        -d '{"run_id": "${{ github.run_id }}"}'

      